# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-07 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='code_01',
            new_name='code01',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='code_010',
            new_name='code010',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='code_02',
            new_name='code02',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='code_03',
            new_name='code03',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='code_04',
            new_name='code04',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='code_05',
            new_name='code05',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='code_06',
            new_name='code06',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='code_07',
            new_name='code07',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='code_08',
            new_name='code08',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='code_09',
            new_name='code09',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text_01',
            new_name='text01',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text_010',
            new_name='text010',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text_02',
            new_name='text02',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text_03',
            new_name='text03',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text_04',
            new_name='text04',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text_05',
            new_name='text05',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text_06',
            new_name='text06',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text_07',
            new_name='text07',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text_08',
            new_name='text08',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text_09',
            new_name='text09',
        ),
    ]
