# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-08 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0002_auto_20171207_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='code01',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='code010',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='code02',
        ),
        migrations.RemoveField(
            model_name='article',
            name='code03',
        ),
        migrations.RemoveField(
            model_name='article',
            name='code04',
        ),
        migrations.RemoveField(
            model_name='article',
            name='code05',
        ),
        migrations.RemoveField(
            model_name='article',
            name='code06',
        ),
        migrations.RemoveField(
            model_name='article',
            name='code07',
        ),
        migrations.RemoveField(
            model_name='article',
            name='code08',
        ),
        migrations.RemoveField(
            model_name='article',
            name='code09',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text01',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text010',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text02',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text03',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text04',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text05',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text06',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text07',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text08',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text09',
        ),
    ]
