# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-12 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0003_auto_20171208_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('date_of_note', models.DateTimeField()),
            ],
        ),
    ]
