# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-12 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0004_usermessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='text',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
