# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-12 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0005_auto_20171212_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
