# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-13 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0008_auto_20171212_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodmessage',
            name='date_of_note',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='date_of_note',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
