# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0009_auto_20171213_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmessage',
            name='admin_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='admin_answer',
            field=models.TextField(blank=True),
        ),
    ]
