# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-13 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0011_usermessage_public_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodMessage',
        ),
    ]
