# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0013_textnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='textnew',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
