# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-15 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0014_textnew_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedMod_GTR2416',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.CharField(max_length=10)),
                ('text', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
