# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-15 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0015_ledmod_gtr2416'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledmod_gtr2416',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
