# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-17 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0017_auto_20171217_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledmod_gtr2416',
            name='text_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ledmod_gtr2416',
            name='text_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ledmod_gtr2416',
            name='text_3',
            field=models.TextField(blank=True),
        ),
    ]
