# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-17 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0018_auto_20171217_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledmod_gtr2416',
            name='numb',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
