# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-17 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0019_auto_20171217_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledmod_gtr2416',
            name='text_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ledmod_gtr2416',
            name='text_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ledmod_gtr2416',
            name='text_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='textnew',
            name='text_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='textnew',
            name='text_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='textnew',
            name='text_6',
            field=models.TextField(blank=True),
        ),
    ]
