# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-21 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0022_auto_20171220_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('numb', models.CharField(blank=True, max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('text_1', models.TextField(blank=True)),
                ('text_2', models.TextField(blank=True)),
                ('text_3', models.TextField(blank=True)),
                ('text_4', models.TextField(blank=True)),
                ('text_5', models.TextField(blank=True)),
                ('text_6', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
