# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-21 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0023_articlebox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlebox',
            name='link',
        ),
        migrations.AddField(
            model_name='articlebox',
            name='image_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articlebox',
            name='image_3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
