# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0024_auto_20171221_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlebox',
            name='tab_dat_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articlebox',
            name='tab_dat_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articlebox',
            name='tab_dat_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articlebox',
            name='tab_dat_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articlebox',
            name='tab_dat_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articlebox',
            name='tab_par_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articlebox',
            name='tab_par_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articlebox',
            name='tab_par_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articlebox',
            name='tab_par_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articlebox',
            name='tab_par_5',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
