# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-24 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0025_auto_20171224_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlebox',
            name='tab_dat_1',
        ),
        migrations.RemoveField(
            model_name='articlebox',
            name='tab_dat_2',
        ),
        migrations.RemoveField(
            model_name='articlebox',
            name='tab_dat_3',
        ),
        migrations.RemoveField(
            model_name='articlebox',
            name='tab_dat_4',
        ),
        migrations.RemoveField(
            model_name='articlebox',
            name='tab_dat_5',
        ),
        migrations.RemoveField(
            model_name='articlebox',
            name='tab_par_1',
        ),
        migrations.RemoveField(
            model_name='articlebox',
            name='tab_par_2',
        ),
        migrations.RemoveField(
            model_name='articlebox',
            name='tab_par_3',
        ),
        migrations.RemoveField(
            model_name='articlebox',
            name='tab_par_4',
        ),
        migrations.RemoveField(
            model_name='articlebox',
            name='tab_par_5',
        ),
    ]
