# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_dj', '0026_auto_20171224_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text_1', models.TextField(blank=True)),
                ('text_2', models.TextField(blank=True)),
                ('text_3', models.TextField(blank=True)),
                ('image_1', models.CharField(blank=True, max_length=200)),
                ('image_2', models.CharField(blank=True, max_length=200)),
                ('image_3', models.CharField(blank=True, max_length=200)),
                ('image_4', models.CharField(blank=True, max_length=200)),
                ('image_5', models.CharField(blank=True, max_length=200)),
                ('image_6', models.CharField(blank=True, max_length=200)),
                ('image_7', models.CharField(blank=True, max_length=200)),
                ('image_8', models.CharField(blank=True, max_length=200)),
                ('image_9', models.CharField(blank=True, max_length=200)),
                ('image_10', models.CharField(blank=True, max_length=200)),
                ('image_11', models.CharField(blank=True, max_length=200)),
                ('image_12', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
